// SQLite DDL for the shared "company brain". Appended to hub-db's migration loop.
export const COMPANY_SCHEMA_STATEMENTS: string[] = [
  `CREATE TABLE IF NOT EXISTS departments (
    id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    folder TEXT NOT NULL,
    reports_to TEXT,
    manages_json TEXT NOT NULL DEFAULT '[]',
    profile_name TEXT,
    skills_json TEXT NOT NULL DEFAULT '[]',
    mcp_json TEXT NOT NULL DEFAULT '[]',
    schedule_cron TEXT,
    budget_minutes_week INTEGER NOT NULL DEFAULT 120,
    approval_policy TEXT NOT NULL DEFAULT 'ask',
    autonomy_level INTEGER NOT NULL DEFAULT 1,
    status TEXT NOT NULL DEFAULT 'idle',
    active INTEGER NOT NULL DEFAULT 1,
    company_id TEXT NOT NULL DEFAULT 'default'
  )`,
  `CREATE TABLE IF NOT EXISTS tasks (
    id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    body TEXT,
    project TEXT,
    dept_id TEXT,
    status TEXT NOT NULL DEFAULT 'inbox',
    priority INTEGER NOT NULL DEFAULT 3,
    origin TEXT,
    blocked_by TEXT NOT NULL DEFAULT '[]',
    emits_on_done TEXT,
    corr_id TEXT,
    checkout_run_id TEXT,
    execution_locked_at INTEGER,
    request_depth INTEGER NOT NULL DEFAULT 0,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    due_at INTEGER,
    result_ref TEXT,
    company_id TEXT NOT NULL DEFAULT 'default'
  )`,
  `CREATE INDEX IF NOT EXISTS idx_tasks_status ON tasks(status, priority DESC)`,
  `CREATE INDEX IF NOT EXISTS idx_tasks_dept ON tasks(dept_id, status)`,
  `CREATE TABLE IF NOT EXISTS handoffs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    task_id TEXT,
    from_dept TEXT,
    to_dept TEXT,
    reason TEXT,
    payload TEXT,
    ts INTEGER NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS memory (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    scope TEXT NOT NULL,
    key TEXT NOT NULL,
    value TEXT NOT NULL,
    source_task TEXT,
    author_dept TEXT,
    ts INTEGER NOT NULL,
    pinned INTEGER NOT NULL DEFAULT 0,
    confidence REAL NOT NULL DEFAULT 1.0
  )`,
  `CREATE INDEX IF NOT EXISTS idx_memory_scope_key ON memory(scope, key)`,
  `CREATE VIRTUAL TABLE IF NOT EXISTS memory_fts USING fts5(value, key, scope)`,
  `CREATE TABLE IF NOT EXISTS approvals (
    id TEXT PRIMARY KEY,
    task_id TEXT,
    dept_id TEXT,
    kind TEXT NOT NULL,
    summary TEXT NOT NULL,
    payload TEXT,
    state TEXT NOT NULL DEFAULT 'pending',
    requested_at INTEGER NOT NULL,
    resolved_at INTEGER,
    decision_note TEXT
  )`,
  `CREATE TABLE IF NOT EXISTS activity_log (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    actor_type TEXT,
    actor TEXT,
    action TEXT,
    entity_type TEXT,
    entity_id TEXT,
    details TEXT,
    ts INTEGER NOT NULL
  )`,
]
